export const SET_NAME_PIZZA = "SET_NAME_PIZZA";
export const EDIT_PIZZA = "EDIT_PIZZA";
export const UPDATE_SELECTOR_ITEM = "UPDATE_SELECTOR_ITEM";
export const UPDATE_INGREDIENT_COUNTER = "UPDATE_INGREDIENT_COUNTER";
export const RESET_BUILDER = "RESET_BUILDER";
export const SET_BUILDER_COMPONENTS = "SET_BUILDER_COMPONENTS";
